from uuid import UUID
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.user import User
from app.models.invite import Invite
from app.schemas.user import (
    InviteCreate,
    InviteValidateResponse,
    RegisterRequest,
    LoginRequest,
    TokenResponse,
    UserResponse,
)
from app.core.security import (
    hash_password,
    verify_password,
    create_access_token,
    get_current_user,
    require_role,
)

router = APIRouter(prefix="/auth", tags=["Auth"])


# ─────────────────────────────────────────
# POST /auth/invite
# Admin only — generates an invite link
# ─────────────────────────────────────────

@router.post("/invite", status_code=status.HTTP_201_CREATED)
def create_invite(
    data: InviteCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role("admin")),
):
    """
    Admin sends: { "role": "worker" } or { "role": "team_lead" }
    Backend creates an Invite row with a fresh UUID token.
    Returns the full invite link for the admin to share.
    """
    invite = Invite(role=data.role)   # token + expires_at auto-generated by model
    db.add(invite)
    db.commit()
    db.refresh(invite)  # reload from DB so invite.token is populated

    invite_link = f"yoursite.com/join?token={invite.token}"

    return {
        "invite_link": invite_link,
        "role": invite.role,
        "expires_at": invite.expires_at,
    }


# ─────────────────────────────────────────
# GET /auth/validate-invite?token=<uuid>
# Public — frontend checks token before showing signup form
# ─────────────────────────────────────────

@router.get("/validate-invite", response_model=InviteValidateResponse)
def validate_invite(token: UUID, db: Session = Depends(get_db)):
    """
    Frontend calls this the moment someone lands on /join?token=...
    Three checks in order: exists → not used → not expired
    Returns role if valid so the form can pre-fill it as read-only.
    """
    invite = db.query(Invite).filter(Invite.token == token).first()

    # Check 1 — does this token exist at all?
    if not invite:
        return InviteValidateResponse(
            valid=False,
            message="This invite link is invalid."
        )

    # Check 2 — has it already been used?
    if invite.used:
        return InviteValidateResponse(
            valid=False,
            message="This invite has already been used."
        )

    # Check 3 — has it expired?
    if invite.expires_at < datetime.now(timezone.utc):
        return InviteValidateResponse(
            valid=False,
            message="This invite link has expired."
        )

    # All checks passed — return the role for the signup form
    return InviteValidateResponse(valid=True, role=invite.role)


# ─────────────────────────────────────────
# POST /auth/register
# Public — worker submits signup form
# ─────────────────────────────────────────

@router.post("/register", status_code=status.HTTP_201_CREATED)
def register(data: RegisterRequest, db: Session = Depends(get_db)):
    """
    Worker sends: token + full_name + phone + password (+ optional email)
    Backend:
      1. Re-validates the token (never trust frontend)
      2. Checks phone/email aren't already taken
      3. Hashes the password
      4. Creates the User row with role from invite
      5. Marks invite as used
      6. Returns success — frontend redirects to /login
    """

    # Step 1 — re-validate the token (same three checks as validate-invite)
    invite = db.query(Invite).filter(Invite.token == data.token).first()

    if not invite or invite.used:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid or already used invite token."
        )

    if invite.expires_at < datetime.now(timezone.utc):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invite token has expired."
        )

    # Step 2 — check phone isn't already registered
    if db.query(User).filter(User.phone == data.phone).first():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="A user with this phone number already exists."
        )

    # Check email uniqueness only if an email was provided
    if data.email:
        if db.query(User).filter(User.email == data.email).first():
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="A user with this email already exists."
            )

    # Step 3 — hash the password before it touches the DB
    hashed = hash_password(data.password)

    # Step 4 — create the user, role comes from the invite not the request
    new_user = User(
        full_name       = data.full_name,
        phone           = data.phone,
        email           = data.email,
        hashed_password = hashed,
        role            = invite.role,   # role is controlled by admin, not user
    )
    db.add(new_user)

    # Step 5 — mark invite as used immediately (single-use enforced)
    invite.used = True

    # Commit both changes atomically — either both save or neither does
    db.commit()

    return {"message": "Registration successful. Please log in."}


# ─────────────────────────────────────────
# POST /auth/login
# Public — any user logs in with phone + password
# ─────────────────────────────────────────

@router.post("/login", response_model=TokenResponse)
def login(data: LoginRequest, db: Session = Depends(get_db)):
    """
    Any user sends: phone + password
    Backend:
      1. Looks up user by phone
      2. Verifies bcrypt hash
      3. Issues JWT containing user_id and role
      4. Returns token — frontend stores it in localStorage
    """

    # Step 1 — find user by phone
    user = db.query(User).filter(User.phone == data.phone).first()

    # Deliberately vague error — don't reveal whether phone exists or not
    if not user or not verify_password(data.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect phone number or password."
        )

    # Step 2 — issue JWT with user_id and role embedded
    token = create_access_token({
        "sub": str(user.id),   # subject = who this token belongs to
        "role": user.role,     # role embedded so routes can check it fast
    })

    return TokenResponse(access_token=token)


# ─────────────────────────────────────────
# GET /auth/me
# Protected — returns the logged-in user's profile
# ─────────────────────────────────────────

@router.get("/me", response_model=UserResponse)
def get_me(current_user: User = Depends(get_current_user)):
    """
    Frontend calls this on load to check who is logged in.
    No DB query needed — get_current_user already fetched the user.
    Returns safe user data (no password hash).
    """
    return current_user